### ISSUE TITLE
hi,is the function performe normal?

### ISSUE THREAD

**Issue by kiwings** [JusticeRage/FFM#11]
HI，
When I try to use !download from remote machine(my ubuntu18.04) to local machine(Kali),it return this error, also the !upload is the same. Which step is wrong?
```
Traceback (most recent call last):
  File "ffm.py", line 167, in <module>
    main()
  File "ffm.py", line 117, in main
    context.active_session.input_driver.handle_input(typed_char)
  File "/root/Tools/FFM/model/driver/input.py", line 87, in handle_input
    self.state(c)
  File "/root/Tools/FFM/model/driver/input.py", line 584, in _state_ground
    if parse_commands(self.input_buffer):
  File "/root/Tools/FFM/commands/command_manager.py", line 43, in parse_commands
    command_instance = c(*args)
  File "/root/Tools/FFM/commands/download_file.py", line 42, in __init__
    if not check_command_existence("xxd") and not check_command_existence("od"):
  File "/root/Tools/FFM/model/driver/input_api.py", line 182, in check_command_existence
    return int(output) == 0
ValueError: invalid literal for int() with base 10: 'command -v xxd >/dev/null ; echo $?\r\necho -n ihxYcJZQkfBctzLVDBDMrMhgqiiNkuGF\r\n0'

```

**Comment by JusticeRage** [comment]
Hi! Thanks a lot for reporting this.
I haven't been able to reproduce this issue. How are you connected to the remote machine? SSH? With or without TTY?
Does this issue happen 100% of the time?
