### ISSUE TITLE
TypeError: Can't instantiate abstract class RunShScript with abstract method _get_output_cleaner

### ISSUE THREAD

**Issue by ice-wzl** [JusticeRage/FFM#15]
- Steps to reproduce:
````
!sh /home/neo/linpeas.sh
Traceback (most recent call last):
  File "/opt/FFM/ffm.py", line 167, in <module>
    main()
  File "/opt/FFM/ffm.py", line 117, in main
    context.active_session.input_driver.handle_input(typed_char)
  File "/opt/FFM/model/driver/input.py", line 87, in handle_input
    self.state(c)
  File "/opt/FFM/model/driver/input.py", line 584, in _state_ground
    if parse_commands(self.input_buffer):
  File "/opt/FFM/commands/command_manager.py", line 43, in parse_commands
    command_instance = c(*args)
TypeError: Can't instantiate abstract class RunShScript with abstract method _get_output_cleaner
````
- Alternative steps to reproduce 
- just `!sh` with no args and it will throw the `TypeError`

**Comment by ice-wzl** [comment]
Issue fixed in commit: `50363fb`
